name: GramTrans
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbd8a1cb_1
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.14=py312h2ec8cdc_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.0=h5888daf_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.1.0=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - liblzma=5.8.1=hb9d3cd8_0
  - liblzma-devel=5.8.1=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.49.1=hee588c1_2
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.0=h7b32b05_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0.1=pyh8b19718_0
  - platformdirs=4.3.7=pyh29332c3_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py312h66e93f0_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - python=3.12.10=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.12=6_cp312
  - pyzmq=26.4.0=py312hbf22597_0
  - readline=8.2=h8c095d6_2
  - setuptools=79.0.1=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.49.1=h9eae976_2
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.2=py312h66e93f0_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.13.2=pyh29332c3_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=hbcc6ac9_0
  - xz-gpl-tools=5.8.1=hbcc6ac9_0
  - xz-tools=5.8.1=hb9d3cd8_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - pip:
      - accelerate==1.2.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.5.0
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - airportsdata==20250224
      - annotated-types==0.7.0
      - anthropic==0.49.0
      - anyio==4.8.0
      - appdirs==1.4.4
      - astor==0.8.1
      - attrs==25.1.0
      - audioread==3.0.1
      - av==14.2.0
      - blake3==1.0.4
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - compressed-tensors==0.9.1
      - contourpy==1.3.1
      - cupy-cuda12x==13.4.0
      - cycler==0.12.1
      - datasets==3.2.0
      - deepspeed==0.16.4
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - docstring-parser==0.16
      - einops==0.8.1
      - email-validator==2.2.0
      - evalplus==0.3.1
      - fastapi==0.115.11
      - fastapi-cli==0.0.7
      - fastrlock==0.8.3
      - ffmpy==0.5.0
      - filelock==3.17.0
      - fire==0.7.0
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gguf==0.10.0
      - gradio==5.18.0
      - gradio-client==1.7.2
      - grpcio==1.72.0rc1
      - grpcio-status==1.71.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.29.2
      - idna==3.10
      - iniconfig==2.0.0
      - interegular==0.3.3
      - jieba==0.42.1
      - jinja2==3.1.6
      - jiter==0.8.2
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.11
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mistral-common==1.5.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - ninja==1.11.1.3
      - nltk==3.9.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.76.0
      - opencv-python-headless==4.11.0.86
      - orjson==3.10.15
      - outlines==0.1.11
      - outlines-core==0.1.26
      - pandas==2.2.3
      - partial-json-parser==0.2.1.1.post5
      - peft==0.12.0
      - pillow==11.1.0
      - pluggy==1.5.0
      - pooch==1.8.2
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.0.2
      - propcache==0.3.0
      - proto-plus==1.26.1
      - protobuf==5.29.4
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==2.13.6
      - pycountry==24.6.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyparsing==3.2.1
      - pytest==8.3.5
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - pytz==2025.1
      - pyyaml==6.0.2
      - ray==2.40.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rich-toolkit==0.13.2
      - rouge-chinese==1.0.3
      - rpds-py==0.23.1
      - rsa==4.9.1
      - ruff==0.9.10
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - shtab==1.7.1
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - sse-starlette==2.2.1
      - starlette==0.46.0
      - stop-sequencer==1.2.3
      - sympy==1.13.1
      - tempdir==0.7.1
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tiktoken==0.9.0
      - tokenizers==0.21.0
      - tomlkit==0.13.2
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.49.0
      - tree-sitter==0.24.0
      - triton==3.1.0
      - trl==0.9.6
      - typer==0.15.2
      - tyro==0.8.14
      - tzdata==2025.1
      - uritemplate==4.1.1
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - vllm==0.7.3
      - watchfiles==1.0.4
      - websockets==15.0.1
      - wget==3.2
      - xformers==0.0.28.post3
      - xgrammar==0.1.11
      - xxhash==3.5.0
      - yarl==1.18.3
      - zmp==6.9
      - zmq==0.0.0
prefix: /root/miniconda3/envs/GramTrans
